### ISSUE TITLE
headerDecoder.msgTypeAsEnum(); returns null sometimes

### ISSUE THREAD

**Issue by skynet21** [real-logic/artio#251] opened 2019-03-14 04:41 UTC
Most of the time headerDecoder.msgTypeAsEnum(); returns the correct value.  Every once in a while it returns null.  If I call it again, it works though.  I've already verified the data is in the mab.  This just started happening when I increased the volume of messages.

      final HeaderDecoder headerDecoder = new HeaderDecoder();
      headerDecoder.decode(mab, 0, length);

      MsgType msgType = headerDecoder.msgTypeAsEnum();
      if (msgType == null) {
        for (int i = 0; i < 100; i++) {
          msgType = headerDecoder.msgTypeAsEnum();
          if (msgType != null) {
            LOGGER.warn("wrapped: retry=" + i + ", msgType=" + msgType + ",mab.byteArray()=" + mab.byteArray().length + ", length=" + length + ", data="
                + StringUtil.fixToString(mab.byteArray()));
            break;
          }
        }
      }

**Comment by RichardWarburton** [comment] 2019-03-14 09:47
Can you please provide an example with an example mab initialization so I can reproduce?

**Comment by skynet21** [comment] 2019-03-15 04:29
Hi Richard,  it seems to happen sparsely but randomly.  Here is a sample fix message:
8=FIX.4.4 9=252 35=G 49=1000000008 56=test 34=829001 52=20190315-04:21:37.163 37=1000000000000 41=0            11=828701       526=385882       1=1000000008 55=BTC/USD[F] 48=12           54=1 60=20190315-04:21:37.163 38=.500000 40=  44=3858.82 192=.500000 640=3858.82 10=158

ByteBuffer messageBuffer = ByteBuffer.allocateDirect(16384);
mab = new MutableAsciiBuffer(messageBuffer);
mab.wrap(data, OFFSET, length);

I am using a generated artio library built about 6 months ago in case that matters.  Thanks

**Comment by RichardWarburton** [comment] 2019-03-17 10:12
Can you confirm that this is reproducible on the latest Artio built from head?

**Comment by RichardWarburton** [comment] 2019-03-20 09:25
Oh also - can you send through the message definition that you think should parse that message buffer if it does work with current head?

**Comment by RichardWarburton** [comment] 2019-04-25 15:33
Closing this issue due to lack of replies.

**Closed by RichardWarburton** 2019-04-25 15:33 UTC
